import * as dotenv from "dotenv";
import { z } from "zod";

dotenv.config();

const EnvSchema = z.object({
  FUND_FIT_TEST_ENV_URL: z.string().url(),
  FUND_FIT_USER_EMAIL: z.string().email(),
  FUND_FIT_USER_NEW_EMAIL: z.string().email(),
  FUND_FIT_USER_PASSWORD: z.string().min(8),
  FUND_FIT_USER_PREVIOUS_PASSWORD: z.string().min(8),
  FUND_FIT_TEST_PASSWORD: z.string().min(8),
  FUND_FIT_LOGIN_PAGE_URL: z.string().url(),
  FUND_FIT_REGISTER_PAGE_URL: z.string().url(),
  FUND_FIT_LANDING_PAGE_URL: z.string().url(),
  FUND_FIT_FORGET_PASSWORD_PAGE_URL: z.string().url(),
  FUND_FIT_DASHBOARD_PAGE_URL: z.string().url(),
  FUND_FIT_START_MATCHING_PAGE_URL: z.string().url(),
  FUND_FIT_MATCHES_PAGE_URL: z.string().url(),
  FUND_FIT_NOTIFICATIONS_PAGE_URL: z.string().url(),

  FUND_FIT_PROFILE_PAGE_URL: z.string().url(),
  FUND_FIT_PROFILE_EDIT_PAGE_URL: z.string().url(),
  FUND_FIT_PROFILE_PASSWORD_SETTING_PAGE_URL: z.string().url(),
  FUND_FIT_PROFILE_EMAIL_SETTING_PAGE_URL: z.string().url(),

  FUND_FIT_PROFILE_BACKGROUND_PAGE_URL: z.string().url(),
  FUND_FIT_PROFILE_BACKGROUND_CREATE_PAGE_URL: z.string().url(),
  FUND_FIT_PROFILE_BACKGROUND_UPDATE_PAGE_URL: z.string().url(),

  FUND_FIT_PROFILE_WORK_PAGE_URL: z.string().url(),
  FUND_FIT_PROFILE_WORK_CREATE_PAGE_URL: z.string().url(),
  FUND_FIT_PROFILE_WORK_UPDATE_PAGE_URL: z.string().url(),

  FUND_FIT_PROFILE_PROJECT_PAGE_URL: z.string().url(),
  FUND_FIT_PROFILE_ATTACHMENT_PAGE_URL: z.string().url(),
  FUND_FIT_CREATE_PROJECT_PAGE_URL: z.string().url(),
});

export const ENV = EnvSchema.parse({
  FUND_FIT_TEST_ENV_URL: process.env.FUND_FIT_TEST_ENV_URL,
  FUND_FIT_USER_EMAIL: process.env.FUND_FIT_USER_EMAIL,
  FUND_FIT_USER_NEW_EMAIL: process.env.FUND_FIT_USER_NEW_EMAIL,
  FUND_FIT_USER_PASSWORD: process.env.FUND_FIT_USER_PASSWORD,
  FUND_FIT_USER_PREVIOUS_PASSWORD: process.env.FUND_FIT_USER_PREVIOUS_PASSWORD,
  FUND_FIT_TEST_PASSWORD: process.env.FUND_FIT_TEST_PASSWORD,
  FUND_FIT_LOGIN_PAGE_URL: process.env.FUND_FIT_LOGIN_PAGE_URL,
  FUND_FIT_REGISTER_PAGE_URL: process.env.FUND_FIT_REGISTER_PAGE_URL,
  FUND_FIT_LANDING_PAGE_URL: process.env.FUND_FIT_LANDING_PAGE_URL,
  FUND_FIT_FORGET_PASSWORD_PAGE_URL:
    process.env.FUND_FIT_FORGET_PASSWORD_PAGE_URL,
  FUND_FIT_DASHBOARD_PAGE_URL: process.env.FUND_FIT_DASHBOARD_PAGE_URL,
  FUND_FIT_START_MATCHING_PAGE_URL:
    process.env.FUND_FIT_START_MATCHING_PAGE_URL,
  FUND_FIT_MATCHES_PAGE_URL: process.env.FUND_FIT_MATCHES_PAGE_URL,
  FUND_FIT_NOTIFICATIONS_PAGE_URL: process.env.FUND_FIT_NOTIFICATIONS_PAGE_URL,

  FUND_FIT_PROFILE_PAGE_URL: process.env.FUND_FIT_PROFILE_PAGE_URL,
  FUND_FIT_PROFILE_EDIT_PAGE_URL: process.env.FUND_FIT_PROFILE_EDIT_PAGE_URL,
  FUND_FIT_PROFILE_PASSWORD_SETTING_PAGE_URL:
    process.env.FUND_FIT_PROFILE_PASSWORD_SETTING_PAGE_URL,
  FUND_FIT_PROFILE_EMAIL_SETTING_PAGE_URL:
    process.env.FUND_FIT_PROFILE_EMAIL_SETTING_PAGE_URL,

  FUND_FIT_PROFILE_BACKGROUND_PAGE_URL:
    process.env.FUND_FIT_PROFILE_BACKGROUND_PAGE_URL,
  FUND_FIT_PROFILE_BACKGROUND_CREATE_PAGE_URL:
    process.env.FUND_FIT_PROFILE_BACKGROUND_CREATE_PAGE_URL,
  FUND_FIT_PROFILE_BACKGROUND_UPDATE_PAGE_URL:
    process.env.FUND_FIT_PROFILE_BACKGROUND_UPDATE_PAGE_URL,

  FUND_FIT_PROFILE_WORK_PAGE_URL: process.env.FUND_FIT_PROFILE_WORK_PAGE_URL,
  FUND_FIT_PROFILE_WORK_CREATE_PAGE_URL:
    process.env.FUND_FIT_PROFILE_WORK_CREATE_PAGE_URL,
  FUND_FIT_PROFILE_WORK_UPDATE_PAGE_URL:
    process.env.FUND_FIT_PROFILE_WORK_UPDATE_PAGE_URL,

  FUND_FIT_PROFILE_PROJECT_PAGE_URL:
    process.env.FUND_FIT_PROFILE_PROJECT_PAGE_URL,
  FUND_FIT_PROFILE_ATTACHMENT_PAGE_URL:
    process.env.FUND_FIT_PROFILE_ATTACHMENT_PAGE_URL,
  FUND_FIT_CREATE_PROJECT_PAGE_URL: process.env.FUND_FIT_CREATE_PROJECT_PAGE_URL,
});
